# Generated by Django 5.1.7 on 2025-04-08 19:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_capacite_salle_capacite_max_salle_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poubelle',
            name='capacite_maximale',
        ),
        migrations.RemoveField(
            model_name='poubelle',
            name='id_unique',
        ),
        migrations.RemoveField(
            model_name='poubelle',
            name='type_dechet',
        ),
        migrations.RemoveField(
            model_name='thermostat',
            name='connectivite',
        ),
        migrations.RemoveField(
            model_name='thermostat',
            name='derniere_interaction',
        ),
        migrations.RemoveField(
            model_name='thermostat',
            name='etat_batterie',
        ),
        migrations.RemoveField(
            model_name='thermostat',
            name='id_unique',
        ),
        migrations.RemoveField(
            model_name='thermostat',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='thermostat',
            name='salle',
        ),
        migrations.AddField(
            model_name='poubelle',
            name='capacite_max',
            field=models.IntegerField(default=38),
        ),
        migrations.AddField(
            model_name='poubelle',
            name='date_maintenance',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poubelle',
            name='en_maintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poubelle',
            name='nom',
            field=models.CharField(default='Poubelle inconnue', max_length=100),
        ),
        migrations.AddField(
            model_name='thermostat',
            name='date_maintenance',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thermostat',
            name='en_maintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='poubelle',
            name='quantite_present',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='poubelle',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poubelles', to='accounts.salle'),
        ),
        migrations.CreateModel(
            name='ReservationOrdinateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('ordinateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ordinateur')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationSalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.salle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet_type', models.CharField(max_length=50)),
                ('objet_id', models.PositiveIntegerField()),
                ('raison', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.BooleanField(default=False)),
                ('date_signalement', models.DateTimeField(default=django.utils.timezone.now)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
