# Generated by Django 5.1.7 on 2025-04-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_niveau_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_de_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='genre',
            field=models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme'), ('Autre', 'Autre')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nom',
            field=models.CharField(default='Inconnu', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='photos_profil/'),
        ),
        migrations.AddField(
            model_name='user',
            name='prenom',
            field=models.CharField(default='Inconnu', max_length=150),
        ),
    ]
